#!/usr/bin/env node
// scripts/gen-strings.mjs — codegen runner for string catalogs.
// Reads shared/strings/catalogs/<locale>.json and emits per-platform consumables.
// See keel playbook 08-string-catalog-i18n.md.
//
// Usage:
//   node scripts/gen-strings.mjs           # regenerate
//   node scripts/gen-strings.mjs --check   # verify in-sync (fails if out of date)
//
// STATUS: skeleton. Wire emit logic for each platform as it appears.

import { readFileSync, readdirSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const CHECK_MODE = process.argv.includes('--check');

const CATALOGS_DIR = join(ROOT, 'shared/strings/catalogs');

// TODO: load all locale catalogs, validate key parity across locales,
// then emit:
//   - Web TS:    src/lib/strings/strings.generated.ts
//   - Swift:     packages/<Core>UI/.../Generated/LocalizedStrings.generated.swift
//   - CF-side:   packages/cf-utils/src/generated/strings.generated.ts
//
// Each emit() output must carry an AUTOGENERATED banner.
//
// In CHECK_MODE, compute the would-be output and compare against the existing file;
// exit 1 on mismatch with a clear error pointing to `npm run strings:gen`.

console.log(`[gen-strings] mode=${CHECK_MODE ? 'check' : 'write'}`);
console.log(`[gen-strings] catalogs=${CATALOGS_DIR}`);
console.log(`[gen-strings] TODO: implement key-parity check + platform emitters`);
process.exit(0);
