#!/usr/bin/env node
// scripts/gen-tokens.mjs — codegen runner for design tokens.
// Reads shared/tokens/tokens.json and emits per-platform consumables.
// See keel playbook 02-design-system.md.
//
// Usage:
//   node scripts/gen-tokens.mjs           # regenerate
//   node scripts/gen-tokens.mjs --check   # verify in-sync (fails if out of date)
//
// STATUS: skeleton. Wire emit logic for each platform as it appears.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const CHECK_MODE = process.argv.includes('--check');

const SOURCE = join(ROOT, 'shared/tokens/tokens.json');
const tokens = JSON.parse(readFileSync(SOURCE, 'utf8'));

// TODO: implement emit() per platform.
//   - Web CSS:  src/ui/tokens.generated.css   (CSS custom properties)
//   - Swift:    packages/<Core>/.../Tokens/<Family>.generated.swift  (struct + static lets)
//   - Kotlin:   packages/<Core>/.../tokens/<Family>.generated.kt    (when Android lands)
//
// Each emit() output must carry a banner like:
//   /* AUTOGENERATED by scripts/gen-tokens.mjs from shared/tokens/tokens.json. DO NOT EDIT. */
//
// In CHECK_MODE, compute the would-be output and compare against the existing file;
// exit 1 on mismatch with a clear error pointing to `npm run tokens:gen`.

console.log(`[gen-tokens] mode=${CHECK_MODE ? 'check' : 'write'}`);
console.log(`[gen-tokens] source=${SOURCE}`);
console.log(`[gen-tokens] TODO: implement platform emitters`);
process.exit(0);
